/**
 * AUTO-GENERATED by scripts/gen-build-info.mjs at build time.
 * DO NOT EDIT MANUALLY — every build derives BUILD_ID from git + build date,
 * so the footer, ?v= cache busters, and vite filename salt can never go stale.
 * SHA: 424a8ed
 */
export const BUILD_ID = '2026.09.10-424a8ed'
export const BUILD_LABEL = `chore(e2e): remove temporary debug specs`
export const BUILD_DATE = '2026.09.10'
/** Shown in site footer — auto-synced with BUILD_ID */
export const FOOTER_VERSION = `BUILD ${BUILD_ID}`
