/**
 * AUTO-GENERATED by scripts/gen-build-info.mjs at build time.
 * DO NOT EDIT MANUALLY — every build derives BUILD_ID from git + build date,
 * so the footer, ?v= cache busters, and vite filename salt can never go stale.
 * SHA: 2b957bb
 */
export const BUILD_ID = '2026.09.16-2b957bb'
export const BUILD_LABEL = `i18n(sw): CORE Swahili for /programs source-watch badge — cover source.* keys (t_64c3969f)`
export const BUILD_DATE = '2026.09.16'
/** Shown in site footer — auto-synced with BUILD_ID */
export const FOOTER_VERSION = `BUILD ${BUILD_ID}`
