/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--mp-canvas-rgb) / <alpha-value>)',
        section: 'rgb(var(--mp-section-rgb) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--mp-card-rgb) / <alpha-value>)',
          muted: 'rgb(var(--mp-card-muted-rgb) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--mp-ink-rgb) / <alpha-value>)',
          secondary: 'rgb(var(--mp-ink-secondary-rgb) / <alpha-value>)',
          muted: 'rgb(var(--mp-ink-muted-rgb) / <alpha-value>)',
          inverse: 'rgb(var(--mp-ink-inverse-rgb) / <alpha-value>)',
        },
        'btc-orange': '#F7931A',
        'btc-orange-deep': '#E07B0F',
        'btc-orange-soft': 'rgb(var(--mp-btc-soft-rgb) / <alpha-value>)',
        status: {
          green: '#16A34A',
          amber: '#D97706',
          red: '#DC2626',
        },
        nostr: {
          violet: '#7C3AED',
          'violet-soft': 'rgb(var(--mp-nostr-soft-rgb) / <alpha-value>)',
        },
        mp: {
          DEFAULT: 'rgb(var(--mp-border-rgb) / <alpha-value>)',
          strong: 'rgb(var(--mp-border-strong-rgb) / <alpha-value>)',
          canvas: 'var(--mp-surface-canvas)',
          section: 'var(--mp-surface-section)',
          card: 'var(--mp-surface-card)',
          'card-aged': 'var(--mp-surface-card-aged)',
          elevated: 'var(--mp-surface-elevated)',
          modal: 'var(--mp-surface-modal)',
          border: 'var(--mp-border-default)',
          'border-subtle': 'var(--mp-border-subtle)',
          'border-strong': 'var(--mp-border-strong)',
          'border-focus': 'var(--mp-border-focus)',
          ink: 'var(--mp-ink-primary)',
          'ink-secondary': 'var(--mp-ink-secondary)',
          'ink-tertiary': 'var(--mp-ink-tertiary)',
          'ink-inverse': 'var(--mp-ink-inverse)',
          'ink-on-accent': 'var(--mp-ink-on-accent)',
          'on-hero': 'var(--mp-ink-on-hero)',
          'hero-headline': 'var(--mp-hero-headline)',
          'on-hero-secondary': 'var(--mp-ink-on-hero-secondary)',
          'on-hero-muted': 'var(--mp-ink-on-hero-muted)',
          'on-hero-subtle': 'var(--mp-ink-on-hero-subtle)',
          'hero-glass': 'var(--mp-surface-hero-glass)',
          btc: 'var(--mp-accent-btc)',
          'btc-text': 'var(--mp-accent-btc-text)',
          'btc-deep': 'var(--mp-accent-btc-deep)',
          'btc-soft': 'var(--mp-accent-btc-soft)',
          ochre: 'var(--mp-accent-ochre)',
          copper: 'var(--mp-accent-copper)',
          wax: 'var(--mp-accent-wax)',
          proof: 'var(--mp-proof-green)',
          'proof-soft': 'var(--mp-proof-green-soft)',
          nostr: 'var(--mp-nostr-violet)',
        },
        sovereign: {
          black: 'rgb(var(--mp-ink-rgb) / <alpha-value>)',
          void: 'rgb(var(--mp-card-rgb) / <alpha-value>)',
          silver: 'rgb(var(--mp-ink-muted-rgb) / <alpha-value>)',
        },
        freedom: { white: 'rgb(var(--mp-ink-rgb) / <alpha-value>)' },
      },
      fontFamily: {
        display: ['var(--mp-font-display)', 'Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['var(--mp-font-body)', 'Inter', 'system-ui', 'sans-serif'],
        chrome: ['var(--mp-font-chrome)', 'IBM Plex Sans', '-apple-system', 'sans-serif'],
        mono: ['var(--mp-font-mono)', 'JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        eyebrow: ['var(--mp-text-eyebrow)', { letterSpacing: 'var(--mp-tracking-eyebrow)', lineHeight: '1.4' }],
        body: ['var(--mp-text-body)', { lineHeight: 'var(--mp-leading-body)' }],
        lg2: ['var(--mp-text-lg)', { lineHeight: '1.5' }],
        h3: ['var(--mp-text-h3)', { lineHeight: '1.15', letterSpacing: 'var(--mp-tracking-display)' }],
        h2: ['var(--mp-text-h2)', { lineHeight: '1.08', letterSpacing: 'var(--mp-tracking-display)' }],
        h1: ['var(--mp-text-h1)', { lineHeight: 'var(--mp-leading-display)', letterSpacing: 'var(--mp-tracking-display)' }],
        hero: ['var(--mp-text-hero)', { lineHeight: 'var(--mp-leading-display)', letterSpacing: 'var(--mp-tracking-display)' }],
      },
      borderRadius: {
        'mp-sm': '8px',
        'mp-md': '12px',
        'mp-lg': '16px',
        'mp-xl': '20px',
        chip: 'var(--mp-radius-chip)',
        card: 'var(--mp-radius-card)',
        panel: 'var(--mp-radius-panel)',
      },
      boxShadow: {
        card: 'var(--mp-shadow-card)',
        'card-hover': 'var(--mp-shadow-card-hover)',
        header: 'var(--mp-shadow-header)',
        'mp-1': 'var(--mp-shadow-1)',
        'mp-2': 'var(--mp-shadow-2)',
        'mp-3': 'var(--mp-shadow-3)',
        'mp-4': 'var(--mp-shadow-4)',
        'mp-glow': 'var(--mp-shadow-glow-btc)',
      },
      backgroundImage: {
        'gradient-radial-soft': 'var(--mp-gradient-radial)',
        'gradient-hero-fade': 'var(--mp-gradient-hero)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-radial-warm': 'var(--gradient-radial-warm)',
        'gradient-scrim-bottom': 'var(--gradient-scrim-bottom)',
        'gradient-seal': 'var(--gradient-seal)',
        guilloche: 'var(--guilloche-pattern)',
        grid: 'var(--grid-pattern)',
      },
      transitionTimingFunction: {
        'spring-snappy': 'var(--spring-snappy)',
        'spring-gentle': 'var(--spring-gentle)',
        'spring-settle': 'var(--spring-settle)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
      animation: {
        'ken-burns': 'ken-burns 24s var(--spring-settle) infinite alternate',
        'fade-up': 'fade-up 0.6s ease-out forwards',
        shimmer: 'shimmer 2s linear infinite',
        'rise-in': 'rise-in var(--duration-slow) var(--spring-gentle) both',
        'bar-grow': 'bar-grow 1.2s var(--spring-gentle) both',
      },
      keyframes: {
        'ken-burns': {
          '0%': { transform: 'scale(1) translate(0, 0)' },
          '100%': { transform: 'scale(1.08) translate(-1%, -1%)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'rise-in': {
          '0%': { opacity: '0', transform: 'translateY(18px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'bar-grow': {
          '0%': { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        },
        'count-flicker': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
}