/** gab.country-trust.v1 — per-country trust envelope (generated by gen-trust-envelopes.mjs). */
export type FreshnessStatus = 'fresh' | 'watch' | 'stale'

export interface CountryTrustEnvelope {
  schema: 'gab.country-trust.v1'
  country: {
    iso2: string
    name: string
    flag?: string | null
    region?: string | null
    category?: string | null
  }
  generated_at: string
  freshness: {
    status: FreshnessStatus
    days_stale: number | null
    verified_at: string | null
    scale: string
    pipeline_sweep?: { status: string; days_stale: number; last_checked: string } | null
  }
  proof: {
    status: 'confirmed' | 'pending' | 'none'
    block: number | null
    stamped_at: string | null
    hash: string | null
    proof_url: string | null
    ots_path: string | null
    in_sync: boolean | null
  }
  scorecard: {
    axes: Record<string, { value: number | null; present: boolean; label: string }>
    note?: string | null
  }
  threshold: {
    min_investment_usd: number | null
    typical_investment_usd: number | null
    history: { date: string | null; field: string; usd: number; note: string }[]
    pathways: { type: string; label: string; min_investment_usd: number | null }[]
  }
  sources: {
    tiers: { official: number; legal: number; secondary: number }
    list: { name: string; tier: 'official' | 'legal' | 'secondary' }[]
    official_urls: string[]
  }
  watch: {
    changed: boolean
    last_probe_at: string | null
    urls: { url: string; status: string | null; last_probed: string | null }[]
  } | null
  audit_trail: {
    date: string | null
    field: string | null
    from: string | null
    to: string | null
    hash: string | null
  }[]
  sovereignty: {
    score: number | null
    stacking_synergy?: string | null
    risk_level?: string | null
    lightning_ready: boolean
    bitcoin_integration?: string | null
  }
}

export interface CountryTrustIndex {
  schema: 'gab.country-trust.v1.index'
  generated_at: string
  count: number
  sweep: { fresh: number; watch: number; stale: number }
  countries: {
    iso2: string
    name: string
    flag?: string | null
    freshness_status: FreshnessStatus
    days_stale: number | null
    proof_status: string
    proof_block: number | null
    min_investment_usd: number | null
    sovereignty_score: number | null
  }[]
}
