#!/usr/bin/env python3
"""Build a single self-hosted flag sprite from flagcdn for all program ISOs.
Composes N flags (w40 = 40x30px) into a grid sprite + generates the iso->offset map.
Run from repo root: python3 scripts/build-flag-sprite.py
"""
import json, os, urllib.request, sys
from PIL import Image, ImageOps

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODES = json.load(open('/tmp/program_iso_codes.json'))  # 50 distinct ISOs

FLAG_W, FLAG_H = 40, 30  # download at 2x display size (display 20x15) for crispness
COLS = 10

def fetch(iso):
    url = f'https://flagcdn.com/w40/{iso}.png'
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read()

os.makedirs('/tmp/flag_dl', exist_ok=True)
imgs, failed = [], []
for iso in CODES:
    p = f'/tmp/flag_dl/{iso}.png'
    if not os.path.exists(p) or os.path.getsize(p) < 20:
        try:
            data = fetch(iso)
            open(p, 'wb').write(data)
        except Exception as e:
            failed.append(iso)
            print(f'  WARN {iso}: {e}')
    try:
        im = Image.open(p).convert('RGBA')
        im = im.resize((FLAG_W, FLAG_H), Image.LANCZOS)
        imgs.append((iso, im))
    except Exception as e:
        failed.append(iso)
        print(f'  WARN open {iso}: {e}')

print(f'composing {len(imgs)} flags, failed: {failed or "none"}')
rows = (len(imgs) + COLS - 1) // COLS
sheet = Image.new('RGBA', (COLS * FLAG_W, rows * FLAG_H), (0, 0, 0, 0))
offsets = {}
for i, (iso, im) in enumerate(imgs):
    r, c = divmod(i, COLS)
    sheet.paste(im, (c * FLAG_W, r * FLAG_H))
    offsets[iso] = {'row': r, 'col': c, 'x': c * FLAG_W, 'y': r * FLAG_H}

out_png = os.path.join(REPO, 'public/images/flags-sprite.png')
sheet.save(out_png, optimize=True)
print('sprite:', out_png, os.path.getsize(out_png), 'bytes', sheet.size)

# webp + avif variants
out_webp = os.path.join(REPO, 'public/images/flags-sprite.webp')
sheet.save(out_webp, 'WEBP', quality=90, method=6)
print('sprite webp:', out_webp, os.path.getsize(out_webp), 'bytes')
try:
    out_avif = os.path.join(REPO, 'public/images/flags-sprite.avif')
    sheet.save(out_avif, 'AVIF', quality=80, speed=6)
    print('sprite avif:', out_avif, os.path.getsize(out_avif), 'bytes')
except Exception as e:
    print('avif unavailable:', e)

# Emit TS map: iso -> offset in a 40x30 grid (displayed at 20x15 via bg-size)
ts = '// AUTO-GENERATED by scripts/build-flag-sprite.py. Do not edit by hand.\n'
ts += '// Sprite: /images/flags-sprite.webp — single request for ALL program flags.\n'
ts += '// Each tile is 40x30px in the sprite, displayed at 20x15 via background-size: 100%.\n'
ts += 'export const FLAG_SPRITE_OFFSETS: Record<string, { x: number; y: number }> = {\n'
for iso in sorted(offsets):
    ts += f"  '{iso}': {{ x: {offsets[iso]['x']}, y: {offsets[iso]['y']} }},\n"
ts += '}\n'
ts += f'\n// Tile dims in the sprite\n'
ts += f'export const FLAG_SPRITE_TILE = {{ w: {FLAG_W}, h: {FLAG_H}, cols: {COLS}, rows: {rows} }}\n'
out_ts = os.path.join(REPO, 'src/lib/flagSprite.ts')
open(out_ts, 'w').write(ts)
print('map:', out_ts, len(offsets), 'entries')
