/**
 * BTC-first currency data anchor — AUTO-GENERATED by scripts/sync-fx-snapshot.mjs.
 * Do not edit by hand; re-run `npm run fx:sync` after dataset re-capture.
 */
export const BTC_USD_AT_CAPTURE = 77328
export const CAPTURE_PRICE_SOURCE = 'coingecko' as const
export const CAPTURED_AT = '2026-08-22T19:38:45.877Z'
